import {ascensionChoices,resolveAscension} from './progress-input.js';
import {weaponGrid} from './weapon-grid.js';
import './planner-tabs.js';
import {levelField} from './level-picker.js';
import {allocate,newGoal,clone,validateGoal,SKILLS,synthesisSuggestions,applySynthesis,completeGoal,estimateFarm,integer} from './engine.js';
import {defaultState,loadState,Store,parseBackup,mergeState,claimRewards,STORAGE_KEY,getStorage,withStorageLock} from './state.js';
import {eventStatus,countdown,nextReset,serverDateToISO,isoToServerInput,formatDate,dayKey} from './time.js';
import {escape as h,fmt,compact,icon,button,badge,empty,bar,portrait,weaponLabel,materialMeta,materialIcon,materialTable} from './ui.js';
import {rewardSlots,readEventRewards,restoreSettingsDraft} from './forms.js';
import {registerPlannerTools} from './webmcp.js';

const app=document.querySelector('#app'),modal=document.querySelector('#modal');
let db,store,plan,loadWarning='',route='summary',search='',element='',weaponFilter='',category='',usedOnly=false,eventView='list',eventMonth=new Date(),editingGoal=null,editingEvent=null,pendingImport=null,toastTimer;
let settingsDraft=null;
const locked=action=>withStorageLock(navigator.locks,action);
function showConflict(){
 if(!store?.conflicted||document.querySelector('#storage-conflict'))return;
 const notice=document.createElement('div');notice.id='storage-conflict';notice.className='notice error';notice.setAttribute('role','alert');
 const message=document.createElement('p');message.textContent=store.saveError;notice.append(message);
 const reload=document.createElement('button');reload.type='button';reload.textContent='Recarregar dados';reload.addEventListener('click',()=>location.reload());notice.append(reload);
 document.querySelector('#main')?.prepend(notice);
}
const nav=[['summary','Resumo'],['characters','Personagens'],['inventory','Inventário'],['farm','Farm'],['events','Eventos'],['settings','Configurações']];
const state=()=>store.state;
const id=()=>crypto.randomUUID();
function toast(text){clearTimeout(toastTimer);const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');toastTimer=setTimeout(()=>el.classList.remove('show'),5000);}
function commit(next,message){store.commit(next);render();if(message)toast(message);}
function openModal(content){modal.classList.toggle('planner-modal',content.includes('id="goal-form"'));modal.innerHTML=content;if(!modal.open)modal.showModal();modal.querySelector('input,select,button')?.focus();}
const modalHeader=(title,sub='')=>`<header class="modal-header"><div><span class="eyebrow">TACET / PLANEJAMENTO</span><h2 id="modal-title">${h(title)}</h2>${sub?`<p>${h(sub)}</p>`:''}</div>${button(icon('close'),'close','aria-label="Fechar janela"','icon-button')}</header>`;
function closeModal(){modal.close();editingGoal=null;editingEvent=null;pendingImport=null;}
function topHeader(title,subtitle,action=''){return `<div class="page-heading"><div><span class="eyebrow">WUTHERING WAVES / PLANNER</span><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>`;}
function resultFor(goal){return plan.goals.find(g=>g.goalId===goal.id);}
function filteredCharacters(){return db.catalog.characters.filter(c=>(!search||c.name.toLowerCase().includes(search.toLowerCase()))&&(!element||c.element===element)&&(!weaponFilter||c.weapon===weaponFilter));}
function characterCard(c){
 const added=state().goals.some(g=>g.charId===c.id);
 return `<article class="character-card ${c.element.toLowerCase()}"><button type="button" class="character-art character-photo" data-action="${added?'edit-char':'add'}" data-id="${h(c.id)}" aria-label="${added?'Editar meta de':'Planejar'} ${h(c.name)} pela foto">${badge(c.element,'element')}${portrait(c,'large')}<span class="rarity">${'★'.repeat(c.rarity)}</span></button><div class="character-body"><div><h3>${h(c.name)}</h3><p>${weaponLabel(c.weapon)}</p></div>${button(added?icon('check'):icon('plus'),added?'edit-char':'add',`data-id="${c.id}" aria-label="${added?'Editar meta de':'Planejar'} ${h(c.name)}"`,'add-character')}</div></article>`;
}
function goalCard(goal,index){
 const c=db.catalog.characters.find(c=>c.id===goal.charId),r=resultFor(goal);
 return `<article class="goal-card"><div class="goal-card-top">${button(portrait(c),'edit',`data-id="${h(goal.id)}" aria-label="Editar meta de ${h(c.name)} pela foto"`,'goal-photo')}<div><div class="eyebrow">PRIORIDADE ${String(index+1).padStart(2,'0')} ${goal.done?'· CONCLUÍDA':''}</div><h3>${h(c.name)}</h3><span class="muted">${c.element} · ${weaponLabel(c.weapon)}</span></div><div class="goal-order">${button('↑','move-up',`data-id="${goal.id}" aria-label="Aumentar prioridade de ${c.name}" ${index===0?'disabled':''}`,'icon-button')}${button('↓','move-down',`data-id="${goal.id}" aria-label="Diminuir prioridade de ${c.name}" ${index===state().goals.length-1?'disabled':''}`,'icon-button')}</div></div><div class="goal-level"><span>Nível <b>${goal.current.level}</b> <span class="muted">→</span> <b>${goal.target.level}</b></span><span>Ascensão ${goal.current.ascension} → ${goal.target.ascension}</span></div>${bar(r.progress)}<div class="progress-caption"><span>${r.missingData.length?'Cálculo parcial · verificar dados':goal.done?'Evolução registrada':'Materiais reservados'}</span><strong>${r.progress}%</strong></div><div class="goal-actions">${button('Ver materiais','detail',`data-id="${goal.id}"`,'text-button')}${button(icon('settings'),'edit',`data-id="${goal.id}" aria-label="Editar meta de ${c.name}"`,'icon-button')}${button(goal.done?'Reabrir':'Registrar evolução',goal.done?'reopen':'complete',`data-id="${goal.id}" ${(!goal.done&&(!r.ready||!r.hasWork))?'disabled':''}`,'small-button')}</div></article>`;
}
function summary(){
 const active=state().goals.filter(g=>!g.done),rows=plan.totals,missing=rows.filter(r=>r.missing>0),ready=plan.goals.filter(g=>g.ready&&g.hasWork).length;
 const pct=rows.length?Math.min(missing.length||plan.goals.some(g=>g.missingData.length)?99:100,Math.round(rows.reduce((s,r)=>s+r.allocated/r.needed,0)/rows.length*100)):0;
 const first=active.find(g=>resultFor(g).rows.some(r=>r.missing>0))||active[0],c=first&&db.catalog.characters.find(c=>c.id===first.charId);
 return topHeader('Seu próximo avanço.','Metas claras. Materiais no lugar. Mais tempo em Solaris-3.',button(icon('plus')+' Nova meta','choose','','primary'))+
 `<section class="stats" aria-label="Resumo do planejamento"><div><span>METAS ATIVAS</span><strong>${String(active.length).padStart(2,'0')}</strong><small>${ready?`${ready} pronta(s) para evoluir`:'Uma etapa de cada vez'}</small></div><div><span>MATERIAIS RESERVADOS</span><strong>${pct}<em>%</em></strong><small>Por tipo de recurso${plan.goals.some(g=>g.missingData.length)?' · cálculo parcial':''}</small></div><div><span>RECURSOS EM FALTA</span><strong>${String(missing.length).padStart(2,'0')}</strong><small>${missing.length?'Tipos de material para buscar':'Seu planejamento começa aqui'}</small></div><div><span>WAVEPLATES / DIA</span><strong>${state().settings.dailyWaveplates}<em> ◈</em></strong><small>Disponibilidade configurada</small></div></section>
 <div class="dashboard-grid"><div class="dashboard-main"><div class="section-heading"><h2>${state().goals.length?'Suas metas de evolução':'Escolha seu primeiro Resonator'}</h2><a href="#characters">Ver personagens ${icon('arrow')}</a></div>${state().goals.length?`<div class="goal-list">${state().goals.map(goalCard).join('')}</div>`:`<p class="section-intro">Escolha um personagem para definir sua meta de evolução.</p><div class="characters-grid home-characters">${db.catalog.characters.slice(0,3).map(characterCard).join('')}</div><div class="onboarding"><span>01 <strong>Defina sua meta</strong></span><span>02 <strong>Informe seu estoque</strong></span><span>03 <strong>Veja o que farmar</strong></span></div>`}
 <div class="section-heading"><h2>Visão dos materiais</h2><a href="#inventory">Abrir inventário ${icon('arrow')}</a></div><section class="panel">${materialTable(rows.slice(0,6),db,{compactView:true})}${rows.length>6?'<a class="panel-footer" href="#farm">Ver todos os materiais →</a>':''}</section></div>
 <aside class="dashboard-aside"><section class="focus-panel"><div class="eyebrow">${icon('farm')} PRÓXIMA PRIORIDADE</div><h2>${c?h(c.name):'Prepare o próximo passo'}</h2><p>${c?'Consulte os materiais restantes desta etapa e a reserva por prioridade.':'Seu plano de farm aparece aqui assim que você adicionar uma meta.'}</p>${missing.length?`<ul class="priority-list">${missing.slice(0,3).map(row=>`<li><span>${h(materialMeta(row.id,db).name)}</span><strong>${compact(row.missing)}</strong></li>`).join('')}</ul>`:''}<a class="focus-link" href="${c?'#farm':'#characters'}">${c?'Organizar meu farm':'Escolher personagem'} ${icon('arrow')}</a></section>
 <section class="panel agenda-preview"><div class="section-heading"><h2>No seu radar</h2>${icon('events')}</div>${state().events.filter(e=>eventStatus(e)!=='Encerrado').slice(0,3).map(e=>`<a class="mini-event" href="#events"><span>${h(e.title)}</span><small>${eventStatus(e)} · ${countdown(eventStatus(e)==='Futuro'?e.start:e.end)}</small></a>`).join('')||'<p class="muted">Nenhum evento agendado.<br>Seu próximo lembrete pode morar aqui.</p>'}<a class="text-link" href="#events">Abrir agenda →</a></section>
 </aside></div>`;
}
function characters(){return topHeader('Personagens','Escolha quem vai receber seus próximos materiais.',button(icon('plus')+' Nova meta','choose','','primary'))+
 `<div class="filter-bar"><label class="search-field">${icon('search')}<input id="search" data-filter="search" type="search" value="${h(search)}" placeholder="Pesquisar personagem" aria-label="Pesquisar personagem"></label><label class="select-label">Elemento<select id="element" data-filter="element"><option value="">Todos</option>${['Aero','Electro','Fusion','Glacio','Havoc','Spectro'].map(v=>`<option ${element===v?'selected':''}>${v}</option>`).join('')}</select></label><label class="select-label">Arma<select id="weapon-filter" data-filter="weapon"><option value="">Todas</option>${['Broadblade','Rectifier','Sword','Pistols','Gauntlets'].map(v=>`<option value="${v}" ${weaponFilter===v?'selected':''}>${weaponLabel(v)}</option>`).join('')}</select></label></div>
 ${state().goals.length?`<div class="section-heading"><h2>Suas metas</h2><span class="muted">A ordem define a reserva de materiais</span></div><div class="goal-grid">${state().goals.map(goalCard).join('')}</div>`:''}<div class="section-heading"><h2>Catálogo de Resonators</h2><span class="muted">${filteredCharacters().length} disponíveis nesta base</span></div><div class="characters-grid">${filteredCharacters().map(characterCard).join('')}</div>${!filteredCharacters().length?empty('Nenhum personagem encontrado','Tente outro filtro. O catálogo local contém seis personagens verificados.'):''}<p class="footnote">Nomes dos materiais preservados em inglês para facilitar a consulta no jogo.</p>`;}
function inventory(){
 const used=new Set(plan.totals.map(t=>t.id));for(const g of plan.goals)for(const k of Object.keys(g.consumption))used.add(k);
 if(plan.totals.some(t=>t.id==='xp-potion'))db.catalog.materials.filter(m=>m.xpKind==='potion').forEach(m=>used.add(m.id));
 if(plan.totals.some(t=>t.id==='xp-energy'))db.catalog.materials.filter(m=>m.xpKind==='energy').forEach(m=>used.add(m.id));
 const materials=db.catalog.materials.filter(m=>(!search||m.name.toLowerCase().includes(search.toLowerCase()))&&(!category||m.category===category)&&(!usedOnly||used.has(m.id)));
 return topHeader('Seu inventário','Um estoque compartilhado por todas as suas metas.',`<div class="button-group">${button(icon('upload')+' Importar','import')}${button(icon('download')+' Exportar','export')}</div>`)+
 `<div class="filter-bar"><label class="search-field">${icon('search')}<input id="search" data-filter="search" type="search" value="${h(search)}" placeholder="Pesquisar material" aria-label="Pesquisar material"></label><label class="select-label">Categoria<select id="category" data-filter="category"><option value="">Todas</option>${[...new Set(db.catalog.materials.map(m=>m.category))].map(c=>`<option ${c===category?'selected':''}>${h(c)}</option>`).join('')}</select></label><label class="check-label"><input id="used" data-filter="used" type="checkbox" ${usedOnly?'checked':''}>Usados nas metas</label></div>
 <p class="inline-info">${icon('info')} Quantidades salvas automaticamente. Criar uma meta reserva recursos; o estoque só diminui ao confirmar o consumo.</p><div class="inventory-grid">${materials.map(m=>{
 const stock=state().inventory[m.id]||0,reserved=stock-(plan.unallocated[m.id]||0),row=plan.totals.find(t=>t.id===m.id);
 return `<article class="inventory-card">${materialIcon(m)}<div class="inventory-info"><h3>${h(m.name)}</h3><p>${h(m.category)} ${m.rarity?'· '+m.rarity+'★':''}</p><small>${used.has(m.id)?`${fmt(reserved)} reservado${row?.missing?' · faltam '+fmt(row.missing):''}`:'Fora das metas atuais'}</small></div><label class="quantity">Estoque<input id="inv-${m.id}" data-stock="${m.id}" type="number" min="0" max="1000000000" step="1" value="${stock}" aria-label="Estoque de ${h(m.name)}"></label></article>`;
 }).join('')}</div>${materials.length?'':empty('Nada por aqui','Ajuste a busca ou os filtros para encontrar um material.')}`;
}
function farm(){
 const rows=plan.totals.filter(r=>r.missing>0),suggestions=synthesisSuggestions(plan,db),cfg=state().settings;
 let knownWave=0,knownCount=0;
 const estimates=rows.map(row=>{
  const m=materialMeta(row.id,db),average=cfg.yields[row.id]||0,activity=db.rules.activities[m.activity],est=estimateFarm(row.missing,average,activity?.waveplates||0,cfg.dailyWaveplates);
  if(est){knownWave+=est.waveplates;knownCount++;}
  return {row,m,average,activity,est};
 });
 return topHeader('Hora de farmar.','A lista segue a prioridade das suas metas. Cada recurso tem um destino.')+
 `<section class="farm-summary"><div>${icon('farm')}<span><strong>${fmt(knownWave)} Waveplates</strong><small>${knownCount}/${rows.length} recursos com rendimento informado</small></span></div><div><strong>${knownWave?Math.ceil(knownWave/cfg.dailyWaveplates)+' dias de energia':'—'}</strong><small>Estimativa parcial · ${cfg.dailyWaveplates}/dia</small></div><div><strong>SOL3 ${Math.min(8,Math.floor(cfg.unionLevel/10)+1)}</strong><small>Nível de União ${cfg.unionLevel} · <a href="#settings">ajustar</a></small></div></section>
 <p class="inline-info">${icon('info')} Drops variam. Informe seu rendimento médio no nível atual; alterar o Nível de União limpa essas premissas. A soma por material não desconta drops simultâneos da mesma atividade.</p>
 <div class="farm-list">${estimates.map(({row,m,average,activity,est},i)=>`<article class="farm-card"><span class="rank">${String(i+1).padStart(2,'0')}</span>${materialIcon(m)}<div class="farm-material"><h3>${h(m.name)}</h3><p>${h(m.origin)}</p><small>Faltam <b>${fmt(row.missing)}</b> ${row.id.startsWith('xp-')?'EXP':'unidades'} · ${activity?.waveplates||0} Waveplates/tentativa</small></div><label class="yield-label">Média por tentativa<input id="yield-${row.id}" type="number" min="0" max="1000000000" step="any" value="${average||''}" data-yield="${row.id}" placeholder="Não verificado" aria-label="Rendimento de ${h(m.name)}"></label><div class="farm-estimate">${est?`<strong>≈ ${fmt(est.runs)} tentativas</strong><small>${est.waveplates?`${fmt(est.waveplates)} Waveplates · ≈ ${est.days} dias de energia`:'Coleta sem Waveplates · dias não estimados'}</small>${m.activity==='weekly'?`<small>Limite compartilhado: ${3-cfg.weeklyClaimsUsed} resgates restantes nesta semana.</small>`:''}`:'<strong>Estimativa indisponível</strong><small>Informe um rendimento observado.</small>'}</div>${button('Onde obter','source',`data-id="${row.id}"`,'text-button')}</article>`).join('')||empty('Tudo no seu ritmo','Não há materiais faltantes. Adicione metas ou confira o inventário.',`<a class="primary button" href="#characters">Planejar personagem</a>`)}</div>
 ${estimates.some(x=>x.m.activity==='weekly'&&x.est)?`<div class="notice">Chefes semanais compartilham 3 resgates. Sua estimativa exige ${estimates.filter(x=>x.m.activity==='weekly'&&x.est).reduce((s,x)=>s+x.est.runs,0)} resgates; após os ${3-cfg.weeklyClaimsUsed} disponíveis, considere semanas adicionais de 3. O total de dias de energia acima não inclui essa espera.</div>`:''}
 <div class="section-heading"><h2>Síntese disponível</h2>${badge('Somente receitas verificadas')}</div><section class="panel synthesis">${suggestions.length?suggestions.map(({recipe,count})=>`<div class="synthesis-row"><p>${Object.entries(recipe.inputs).map(([id,n])=>`${fmt(n*count)} ${h(materialMeta(id,db).name)}`).join(' + ')} <b>→</b> ${Object.entries(recipe.outputs).map(([id,n])=>`${fmt(n*count)} ${h(materialMeta(id,db).name)}`).join(' + ')}</p>${button('Revisar síntese','synthesize',`data-id="${recipe.id}" data-count="${count}"`,'small-button')}</div>`).join(''):'<p class="muted">Nenhuma sugestão com os recursos livres. Materiais já reservados para outras metas são protegidos.</p>'}<p class="footnote">A base contém duas receitas LF → MF (Howler e Whisperin). Síntese não é estoque: confirme a operação para registrar o consumo.</p></section>
 <div class="section-heading"><h2>Distribuição completa</h2></div><section class="panel">${materialTable(plan.totals,db)}</section><p class="footnote">¹ Disponível nesta visão: estoque total. Em uma meta: saldo antes de atender aquela prioridade. Progresso é a média de cobertura por recurso, sem misturar unidades com créditos.</p>`;
}
function eventCard(e){const status=eventStatus(e),done=e.tasks.filter(t=>t.done).length,pct=e.tasks.length?Math.round(done/e.tasks.length*100):0;
 return `<article class="event-card"><div class="event-heading"><div>${badge('Pessoal')} ${badge(status,status==='Ativo'?'green':'')}<h3>${h(e.title)}</h3><p>${formatDate(e.start,state().settings.timeZone)} → ${formatDate(e.end,state().settings.timeZone)}</p></div><div class="countdown">${status==='Encerrado'?'Encerrado':countdown(status==='Futuro'?e.start:e.end)}<small>${status==='Futuro'?'para começar':status==='Ativo'?'para terminar':''}</small></div></div>${bar(pct,'Objetivos concluídos')}<div class="checklist">${e.tasks.map((t,i)=>`<label><input type="checkbox" data-task="${e.id}" data-index="${i}" ${t.done?'checked':''} ${e.claimed?'disabled':''}><span class="${t.done?'checked':''}">${h(t.text)}</span></label>`).join('')}</div><div class="event-rewards"><span>${e.claimed?'Recebimento registrado':'Recompensas previstas · informadas por você'}</span><p>${Object.entries(e.rewards).map(([id,n])=>`${fmt(n)} ${h(materialMeta(id,db).name)}`).join(' · ')||'Nenhuma recompensa cadastrada'}</p></div><div class="event-actions">${button('Editar','edit-event',`data-id="${e.id}"`,'text-button')}${button('Excluir','remove-event',`data-id="${e.id}"`,'text-button danger')}${Object.keys(e.rewards).length?button(e.claimed?'Recebido ✓':'Registrar recebimento','claim',`data-id="${e.id}" ${e.claimed||done<e.tasks.length?'disabled':''}`,'small-button'):''}<span class="muted">${done}/${e.tasks.length} objetivos</span></div></article>`;
}
function calendar(){
 const year=eventMonth.getFullYear(),month=eventMonth.getMonth(),days=new Date(year,month+1,0).getDate(),start=(new Date(year,month,1).getDay()+6)%7;
 const today=dayKey(Date.now(),state().settings.timeZone);
 return `<section class="panel calendar-panel"><div class="calendar-heading">${button('‹','prev-month','aria-label="Mês anterior"','icon-button')}<h2>${new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(eventMonth)}</h2>${button('›','next-month','aria-label="Próximo mês"','icon-button')}</div><div class="calendar-grid">${['SEG','TER','QUA','QUI','SEX','SÁB','DOM'].map(d=>`<span class="weekday">${d}</span>`).join('')}${Array.from({length:start},()=>'<div class="calendar-day blank"></div>').join('')}${Array.from({length:days},(_,i)=>{
 const key=`${year}-${String(month+1).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`,events=state().events.filter(e=>key>=dayKey(e.start,state().settings.timeZone)&&key<=dayKey(Date.parse(e.end)-1,state().settings.timeZone));
 return `<div class="calendar-day ${today===key?'today':''}"><span>${i+1}</span>${events.map(e=>button(h(e.title),'edit-event',`data-id="${e.id}"`,'calendar-event')).join('')}</div>`;
 }).join('')}</div></section>`;
}
function events(){return topHeader('Sua agenda em Solaris-3','Eventos, lembretes e objetivos sem perder o prazo.',button(icon('plus')+' Novo evento','new-event','','primary'))+
 `<div class="events-toolbar"><div class="segmented">${button('Lista','event-list',`aria-pressed="${eventView==='list'}"`,eventView==='list'?'selected':'')}${button('Calendário','event-calendar',`aria-pressed="${eventView==='calendar'}"`,eventView==='calendar'?'selected':'')}</div><span class="muted">Exibição: ${h(state().settings.timeZone)} · servidor ${state().settings.server}</span></div>
 <div class="notice">${icon('info')} Calendário oficial atual não verificado. Cadastre eventos pessoais com as datas do servidor; recompensas previstas ficam separadas do inventário. </div>
 ${eventView==='calendar'?calendar():state().events.length?`<div class="events-list">${[...state().events].sort((a,b)=>Date.parse(a.start)-Date.parse(b.start)).map(eventCard).join('')}</div>`:empty('Espaço para o que vem a seguir','Crie um lembrete de farm, uma meta semanal ou acompanhe um evento do jogo.',button(icon('plus')+' Criar meu primeiro evento','new-event','','primary'))}`;}
function settings(){return topHeader('Seu terminal','Ajuste o planejamento ao seu ritmo.')+
 `<div class="settings-grid"><section class="panel settings-panel"><h2>Conta e disponibilidade</h2><form id="settings-form"><label>Servidor<select name="server">${Object.keys(db.rules.servers).map(s=>`<option ${s===state().settings.server?'selected':''}>${s}</option>`).join('')}</select></label><label>Fuso de exibição<select name="timeZone">${[...new Set(['America/Sao_Paulo','America/Manaus','America/New_York','Europe/Lisbon','Europe/London','Asia/Shanghai','Asia/Tokyo','UTC',state().settings.timeZone])].map(s=>`<option ${s===state().settings.timeZone?'selected':''}>${s}</option>`).join('')}</select></label><div class="form-columns"><label>Nível de União<input name="unionLevel" type="number" min="1" max="80" value="${state().settings.unionLevel}" required></label><label>Waveplates por dia<input name="dailyWaveplates" type="number" min="1" max="10000" value="${state().settings.dailyWaveplates}" required></label></div><label>Recompensas semanais já resgatadas<input name="weeklyClaimsUsed" type="number" min="0" max="3" value="${state().settings.weeklyClaimsUsed}" required></label><p class="footnote">Resets às 04:00 do servidor. O contador semanal é renovado na segunda-feira. Seu servidor usa UTC${db.rules.servers[state().settings.server]>=0?'+':''}${db.rules.servers[state().settings.server]} fixo.</p><button class="primary" type="submit">Salvar configurações</button></form></section>
 <section class="panel settings-panel"><h2>Seus dados, com você</h2><p>Salvamento local neste navegador. Um backup leva suas metas, estoque, eventos e configurações para outro dispositivo.</p><div class="button-group">${button(icon('download')+' Exportar backup','export')}${button(icon('upload')+' Importar backup','import')}</div>${button(icon('undo')+' Desfazer última alteração','undo',store.history.length?'':'disabled')}<p class="footnote">Até 20 alterações podem ser desfeitas enquanto a página estiver aberta. Backups completos usam o formato versão 1.</p>${loadWarning?`<div class="notice">${h(loadWarning)}</div>${button('Baixar cópia de recuperação','recovery')}`:''}<h3>Cobertura desta base</h3><ul class="coverage"><li>${db.catalog.characters.length} personagens · nível 1–90 e cinco Fortes.</li><li>${db.catalog.weapons.length} armas · custos por raridade e etapa.</li><li>${db.catalog.materials.length} materiais com imagens · ${db.recipes.length} receitas verificadas.</li><li>EXP por nível para personagens e armas de 1 a 5 estrelas.</li><li>Nós inerentes e bônus: custos ou pré-requisitos não verificados.</li><li>Rendimentos de farm: informados por você, sem taxas inventadas.</li><li>Eventos oficiais atuais: catálogo vazio; cadastro pessoal funcional.</li></ul></section></div>
 `;}

function render(preserve=false){
 const previousIndicator=document.querySelector('.nav-indicator')?.getBoundingClientRect();
 const focus=preserve?document.activeElement?.id:null,selection=preserve&&document.activeElement?.type==='search'?document.activeElement.selectionStart:null;
 plan=allocate(state().goals,state().inventory,db);
 const daily=nextReset(Date.now(),db.rules.servers[state().settings.server]);
 app.innerHTML=`<aside class="sidebar"><a class="brand" href="#summary" aria-label="Tacet, resumo"><img src="./assets/logo.png" width="1927" height="816" alt="Tacet"></a><div class="sidebar-label">SEU TERMINAL</div><nav aria-label="Navegação principal">${nav.map(([key,label])=>`<a href="#${key}" class="${route===key?'active':''}" ${route===key?'aria-current="page"':''}>${icon(key)}<span>${label}</span>${key==='characters'&&state().goals.length?`<b>${state().goals.length}</b>`:''}</a>`).join('')}</nav><div class="sidebar-bottom"><div class="server-status">${icon('clock')}<div>Próximo reset<small>${countdown(new Date(daily).toISOString())} · ${state().settings.server}</small></div></div><div class="local-status">${icon('check')} ${store.saveError?'Falha ao salvar':'Salvo neste dispositivo'}</div><span class="version">TACET / v1.0 · FAN PROJECT</span></div></aside>
 <div class="workspace"><header class="topbar"><a class="mobile-brand" href="#summary" aria-label="Tacet, resumo"><img src="./assets/logo.png" width="1927" height="816" alt="Tacet"></a><div class="breadcrumb">Terminal <span>/</span> <strong>${nav.find(n=>n[0]===route)?.[1]}</strong></div><div class="topbar-right">${button(icon('undo'),'undo',`aria-label="Desfazer última alteração" ${store.history.length?'':'disabled'}`,'icon-button')}<a class="union-badge" href="#settings">UL ${state().settings.unionLevel}</a><span class="avatar">R</span></div></header><main id="main" tabindex="-1">${store.saveError&&!store.conflicted?`<div class="notice error" role="alert">${h(store.saveError)}</div>`:''}${({summary,characters,inventory,farm,events,settings}[route]||summary)()}</main><footer class="page-footer"><span>Feito para explorar. Planejado para evoluir.</span></footer></div>`;
 restoreSettingsDraft(document.querySelector('#settings-form'),settingsDraft);
 showConflict();
 const menu=document.querySelector('.sidebar nav');
 if(menu){
  const index=Math.max(0,nav.findIndex(([key])=>key===route));
  const indicator=document.createElement('span');indicator.className='nav-indicator';indicator.setAttribute('aria-hidden','true');
  indicator.style.setProperty('--nav-index',index);indicator.style.setProperty('--nav-column',index%3);indicator.style.setProperty('--nav-row',Math.floor(index/3));
  menu.prepend(indicator);
  const current=indicator.getBoundingClientRect();
  if(previousIndicator&&!window.matchMedia?.('(prefers-reduced-motion: reduce)').matches){
   const x=previousIndicator.left-current.left,y=previousIndicator.top-current.top;
   if(x||y)indicator.animate?.([{transform:`translate(${x}px,${y}px)`},{transform:'translate(0,0)'}],{duration:320,easing:'cubic-bezier(.22,1,.36,1)'});
  }
 }
 if(focus){const el=document.getElementById(focus);el?.focus();if(selection!==null&&el?.type==='search')el.setSelectionRange(selection,selection);}
}

function choose(){openModal(modalHeader('Quem vamos evoluir?','Escolha um personagem da base local.')+`<div class="modal-content"><label class="search-field">${icon('search')}<input type="search" id="picker-search" placeholder="Pesquisar personagem" aria-label="Pesquisar no seletor de personagens"></label><p id="picker-empty" hidden>Nenhum personagem encontrado.</p><div class="picker-grid">${db.catalog.characters.map(c=>`<button type="button" class="picker-character" data-action="${state().goals.some(g=>g.charId===c.id)?'edit-char':'add'}" data-id="${c.id}">${portrait(c)}<strong>${c.name}</strong><small>${c.element} · ${weaponLabel(c.weapon)}</small></button>`).join('')}</div></div>`);}
function progressFields(prefix,p,heading,weapon=false){return `<fieldset><legend>${heading}</legend><div class="combined-progress" data-progress="${prefix}" data-max-ascension="${weapon?.maxAscension??6}">${levelField(prefix,p.level,weapon?.maxLevel||90)}<input type="hidden" name="${prefix}-ascension" value="${p.ascension}"><button type="button" class="ascension-toggle" data-action="toggle-ascension" aria-label="Ascensão"><img src="./assets/planner-icons/ascension-clear.png" alt=""></button><small class="ascension-hint"></small></div></fieldset>`;}
function syncAscensionFields(){document.querySelectorAll('.combined-progress').forEach(field=>{const input=field.querySelector('input[type=number]'),stage=field.querySelector('input[type=hidden]'),button=field.querySelector('.ascension-toggle'),level=Number(input.value),max=Number(field.dataset.maxAscension),choices=ascensionChoices(level,db.rules.caps,max);stage.value=resolveAscension(level,Number(stage.value),db.rules.caps,max);const ascended=choices.length===2?Number(stage.value)===choices[1]:Number(stage.value)>0;button.disabled=choices.length!==2;button.setAttribute('aria-pressed',String(ascended));button.setAttribute('aria-label',choices.length===2?(ascended?'Ascendido: voltar para antes da ascensão':'Sem ascensão: marcar como ascendido'):'Ascensão definida pelo nível');button.title=choices.length===2?'Clique para alternar antes/depois da ascensão':'A ascensão acompanha este nível';field.querySelector('.ascension-hint').textContent=choices.length===2?(ascended?'Depois da ascensão':'Antes da ascensão'):'Ascensão '+stage.value+' · limite '+db.rules.caps[stage.value];});}
function goalForm(goal){editingGoal=clone(goal);const c=db.catalog.characters.find(c=>c.id===goal.charId),w=goal.weapon,art=db['character-art']?.[c.id];
 openModal(`<header class="planner-hero"><img class="planner-banner" src="${h(art?.banner||c.image)}" alt=""><div class="planner-identity"><img class="planner-avatar" src="${h(art?.icon||c.image)}" alt="${h(c.name)}"><div><span class="eyebrow">PLANEJAR EVOLUÇÃO</span><h2 id="modal-title">${h(c.name)}</h2><p>${h(c.element)} · ${weaponLabel(c.weapon)} <span class="planner-stars">${'★'.repeat(c.rarity)}</span></p></div></div>${button(icon('close'),'close','aria-label="Fechar janela"','icon-button planner-close')}</header><form id="goal-form"><div class="sequence-bar"><div><strong>Cadeia de Ressonância</strong><span>Cópias extras do personagem</span></div><div class="sequence-options" role="radiogroup" aria-label="Cópias extras do personagem">${Array.from({length:7},(_,i)=>`<label title="${i} cópias extras"><input type="radio" name="sequence" value="${i}" ${(goal.sequence??0)===i?'checked':''}><span>S${i}</span></label>`).join('')}</div></div><div class="planner-tabs" role="tablist" aria-label="Etapas de evolução">${[['level','Nível'],['forte','Fortes'],['weapon','Arma']].map(([key,label],i)=>`<button type="button" role="tab" id="planner-tab-${key}" data-planner-tab="${key}" aria-controls="planner-panel-${key}" aria-selected="${i===0}" tabindex="${i===0?0:-1}"><img src="./assets/planner-icons/${key}.png" alt="">${label}</button>`).join('')}</div><div class="modal-content planner-content"><section id="planner-panel-level" data-planner-panel="level" role="tabpanel" aria-labelledby="planner-tab-level">${c.sharedProgress?'<p class="notice">O Rover compartilha nível e ascensão entre os elementos. Esses custos entram uma vez, por prioridade; os Fortes são separados.</p>':''}<div class="form-section-heading"><h3>Até onde vamos evoluir?</h3><span class="muted">Atual → Meta</span></div><div class="form-columns">${progressFields('current',goal.current,'Estado atual')}${progressFields('target',goal.target,'Meta desejada')}</div><p class="footnote">Digite ou escolha o nível. Nos limites de ascensão, clique no símbolo ao lado: apagado = antes de ascender; aceso = depois.</p>
 </section><section id="planner-panel-forte" data-planner-panel="forte" role="tabpanel" aria-labelledby="planner-tab-forte" hidden><div class="form-section-heading"><h3>Aprimore seus Fortes</h3><span class="muted">Atual → Meta</span></div><div class="skills-grid"><span>Habilidade</span><span>Atual</span><span>Meta</span>${SKILLS.map((name,i)=>`<label for="skill-current-${i}">${name}</label><input id="skill-current-${i}" name="skill-current-${i}" type="number" min="1" max="10" value="${goal.current.skills[i]}" aria-label="${name}, atual"><input name="skill-target-${i}" type="number" min="1" max="10" value="${goal.target.skills[i]}" aria-label="${name}, meta">`).join('')}</div><p class="footnote">Limites por ascensão 0–6: 1, 1, 3, 4, 6, 8 e 10. Outro Skill não tem nível de melhoria.</p></section>
 <section id="planner-panel-weapon" data-planner-panel="weapon" role="tabpanel" aria-labelledby="planner-tab-weapon" hidden><div class="form-section-heading"><h3>Prepare sua arma</h3><span class="muted">${weaponLabel(c.weapon)}</span></div>${weaponGrid(db.catalog.weapons.filter(item=>item.type===c.weapon),w?.id,db['weapon-stats'])}<div id="weapon-info"></div><div id="weapon-progress" class="form-columns">${progressFields('weapon-current',w?.current||{level:1,ascension:0,xp:0},'Arma atual',db.catalog.weapons.find(x=>x.id===w?.id))}${progressFields('weapon-target',w?.target||{level:20,ascension:0,xp:0},'Meta da arma',db.catalog.weapons.find(x=>x.id===w?.id))}</div></section>
 <section class="goal-preview" id="goal-preview" aria-live="polite"></section><section id="goal-stock-editor" hidden></section><p class="footnote">Salvar a meta não consome recursos do inventário.</p><p id="form-error" class="form-error" role="alert"></p></div><footer class="modal-footer">${state().goals.some(g=>g.id===goal.id)?button('Excluir meta','remove',`data-id="${goal.id}"`,'text-button danger'):button('Voltar','choose','','text-button')}<div>${button('Cancelar','close')}${button('Feito ✓','finish-goal','id="finish-goal" disabled','primary')}<button type="submit">Salvar meta ${icon('check')}</button></div></footer></form>`);
 updateGoalPreview();
}
function updateWeaponInfo(){
 const el=document.querySelector('#weapon-info');if(!el)return;
 const w=db.catalog.weapons.find(w=>w.id===document.querySelector('[name="weapon-id"]').value);
 if(!w){el.innerHTML='<p class="footnote">Selecione uma arma para conferir seus materiais e configurar a evolução.</p>';return;}
 const ids=[...new Set((w.ascensionCosts||[]).flatMap(cost=>Object.keys(cost)))].filter(id=>id!=='shell');
 el.innerHTML=`<div class="weapon-heading">${w.image?`<img src="${h(w.image)}" alt="${h(w.name)}" width="72" height="72">`:''}<div><h3>${h(w.name)}</h3><p>${w.rarity}★ · ${weaponLabel(w.type)} · nível máximo ${w.maxLevel||90}</p></div></div><p class="footnote">Materiais de ascensão — as quantidades necessárias são calculadas entre o estado atual e a meta.</p><div class="weapon-materials">${ids.map(id=>{const m=materialMeta(id,db);return `<span>${materialIcon(m)}<span>${h(m.name)}</span></span>`;}).join('')}</div>`;
}
function readGoal(){const fd=new FormData(document.querySelector('#goal-form')),g=clone(editingGoal),num=name=>Number(fd.get(name));
 for(const k of ['current','target']){g[k]={level:num(k+'-level'),ascension:num(k+'-ascension'),xp:k==='current'&&num(k+'-level')===editingGoal.current.level&&num(k+'-ascension')===editingGoal.current.ascension?editingGoal.current.xp:0,skills:SKILLS.map((_,i)=>num(`skill-${k}-${i}`)),unlocks:[...editingGoal[k].unlocks]};}
 g.weapon=fd.get('weapon-id')?{id:fd.get('weapon-id'),current:{level:num('weapon-current-level'),ascension:num('weapon-current-ascension'),xp:fd.get('weapon-id')===editingGoal.weapon?.id&&num('weapon-current-level')===editingGoal.weapon.current.level&&num('weapon-current-ascension')===editingGoal.weapon.current.ascension?editingGoal.weapon.current.xp:0},target:{level:num('weapon-target-level'),ascension:num('weapon-target-ascension'),xp:0}}:null;g.sequence=num('sequence');g.done=false;return g;
}
function previewMaterials(rows){return `<h3>Materiais para esta meta</h3><p class="preview-hint">Clique em um material para editar seu estoque.</p><div class="preview-materials">${rows.map(row=>{const m=materialMeta(row.id,db);return `<button type="button" class="preview-material" data-action="edit-goal-stock" data-id="${h(row.id)}" aria-label="Editar estoque de ${h(m.name)}">${materialIcon(m)}<div><strong>${h(m.name)}</strong><span>${fmt(row.needed)} ${row.id.startsWith("xp-")?"EXP":"necessários"}</span><small class="${row.missing?"missing":"complete"}">${row.missing?`Faltam ${fmt(row.missing)}`:"Já disponível ✓"}</small></div></button>`;}).join("")||"<p>Nenhum material necessário para esta meta.</p>"}</div>`;}
function updateGoalPreview(){syncAscensionFields();updateWeaponInfo();const el=document.querySelector('#goal-preview');if(!el)return;const finish=document.querySelector('#finish-goal');finish.disabled=true;try{const goal=readGoal();validateGoal(goal,db);const goals=state().goals.map(g=>g.id===goal.id?goal:g);if(!goals.some(g=>g.id===goal.id))goals.push(goal);const result=allocate(goals,state().inventory,db).goals.find(g=>g.goalId===goal.id);finish.disabled=!result.ready||!result.hasWork||db.rules.union[goal.target.ascension]>state().settings.unionLevel||(goal.weapon&&db.rules.union[goal.weapon.target.ascension]>state().settings.unionLevel);finish.title=finish.disabled?'Reúna os materiais e confira o Nível de União para concluir':'Registrar evolução e consumir os materiais reservados';el.innerHTML=`<div><strong>${result.rows.length} recursos</strong><span>${result.progress}% reservado · prioridade ${goals.findIndex(g=>g.id===goal.id)+1}</span></div>${result.missingData.length?`<p class="warning-text">${h(result.missingData.join(' · '))}</p>`:''}${previewMaterials(result.rows)}${result.exp.map(x=>`<p>${x.kind==='potion'?'Personagem':'Arma'}: ${fmt(x.needed)} EXP necessária${x.surplus?' · combinação com '+fmt(x.surplus)+' EXP excedente':''}.</p>`).join('')}`;}catch(error){el.innerHTML=`<p class="warning-text">${h(error.message)}</p>`;}}
function detail(goal){const c=db.catalog.characters.find(c=>c.id===goal.charId),r=resultFor(goal);openModal(modalHeader(`${c.name} · materiais`,`Prioridade ${state().goals.indexOf(goal)+1}. Disponível = saldo após atender as metas anteriores.`)+`<div class="modal-content">${r.missingData.map(msg=>`<p class="notice">${h(msg)}</p>`).join('')}${materialTable(r.rows,db)}${r.exp.map(exp=>`<section class="exp-detail"><h3>${exp.kind==='potion'?'Poções de ressonância':'Núcleos de energia'}</h3><p>${Object.entries(exp.items).map(([id,n])=>`${fmt(n)} ${h(materialMeta(id,db).name)}`).join(' + ')||'Nenhum consumível disponível'}</p><p>${fmt(exp.allocated)} / ${fmt(exp.needed)} EXP coberta · ${fmt(exp.missing)} EXP faltante.</p>${exp.surplus?`<p class="warning-text">${fmt(exp.surplus)} EXP excedente na combinação. Confira a EXP final e eventuais devoluções no jogo antes de registrar.</p>`:''}</section>`).join('')}<p class="footnote">A sugestão minimiza a EXP excedente, depois a quantidade de consumíveis. Reservas de EXP usam os itens reais do estoque. Experiência obtida em combate pode ser informada como EXP parcial.</p></div><footer class="modal-footer">${button('Editar meta','edit',`data-id="${goal.id}"`)}${button('Registrar evolução','complete',`data-id="${goal.id}" ${!r.ready||!r.hasWork?'disabled':''}`,'primary')}</footer>`);}
function completion(goal){const r=resultFor(goal),c=db.catalog.characters.find(c=>c.id===goal.charId);if(!r.ready||!r.hasWork)throw Error('Faltam materiais ou há dados não verificados.');openModal(modalHeader(`Registrar evolução de ${c.name}`,'Confirme após realizar a evolução no jogo.')+`<form id="completion-form" data-id="${goal.id}"><div class="modal-content"><p>Estado: nível ${goal.current.level} → ${goal.target.level}, ascensão ${goal.current.ascension} → ${goal.target.ascension}. Estes recursos serão descontados:</p><ul class="consumption-list">${Object.entries(r.consumption).map(([id,n])=>`<li><span>${h(materialMeta(id,db).name)}</span><strong>${fmt(n)}</strong></li>`).join('')}</ul>${r.exp.some(x=>x.surplus)?`<div class="notice">Há EXP excedente na sugestão (${r.exp.map(x=>`${x.kind==='potion'?'personagem':'arma'}: ${fmt(x.surplus)}`).join('; ')}). Confira os consumíveis e eventuais devoluções no jogo. Esta reserva calcula créditos pela EXP necessária, sem prever devoluções. Se o consumo diferir, ajuste o consumo real e as devoluções abaixo.</div>`:''}<div class="form-columns"><label>EXP parcial final do personagem<input name="characterXp" type="number" min="0" value="${goal.current.level===goal.target.level?goal.current.xp:0}" required></label>${goal.weapon?'<label>EXP parcial final da arma<input name="weaponXp" type="number" min="0" value="'+(goal.weapon.current.level===goal.weapon.target.level?goal.weapon.current.xp:0)+'" required></label>':''}</div><label class="check-label"><input type="checkbox" required>Conferi o consumo acima e realizei esta evolução no jogo.</label><p class="footnote">Registre devoluções no ajuste de consumo real. Se ultrapassou o nível desejado, ajuste a meta antes de concluir. A operação pode ser desfeita.</p><p id="form-error" role="alert" class="form-error"></p></div><footer class="modal-footer">${button('Cancelar','close')}<button class="primary" type="submit">Confirmar evolução</button></footer></form>`);}

function addActualLedger(goalId){
 const r=plan.goals.find(g=>g.goalId===goalId);if(!r?.exp.length)return;
 const ledger=document.createElement('details');ledger.className='form-details';
 const xpMaterials=db.catalog.materials.filter(m=>r.exp.some(e=>e.kind===m.xpKind));
 ledger.innerHTML=`<summary>Ajustar consumo real e devoluções de EXP</summary><p class="footnote">Se o jogo consumiu outra combinação ou devolveu itens ao atingir o limite, informe os valores reais. As ascensões e os Fortes mantêm seus custos verificados.</p><label>Shell Credits realmente consumidos<input name="actual-shell" type="number" min="0" max="1000000000" value="${r.consumption.shell||0}"></label><div class="skills-grid"><span>Consumível</span><span>Consumido</span><span>Devolvido</span>${xpMaterials.map(m=>`<label>${h(m.name)}</label><input name="actual-${m.id}" type="number" min="0" max="1000000000" value="${r.consumption[m.id]||0}" aria-label="Consumo real de ${h(m.name)}"><input name="refund-${m.id}" type="number" min="0" max="1000000000" value="0" aria-label="Devolução de ${h(m.name)}">`).join('')}</div>`;
 document.querySelector('#completion-form .consumption-list').after(ledger);
}
function eventForm(event=null){editingEvent=event?clone(event):null;const offset=db.rules.servers[state().settings.server],start=event?.start||new Date().toISOString(),end=event?.end||new Date(Date.now()+86400000).toISOString(),reward=Object.entries(event?.rewards||{});
 openModal(modalHeader(event?'Editar evento':'Novo evento pessoal',`Datas no horário do servidor ${state().settings.server} (UTC${offset>=0?'+':''}${offset}).`)+`<form id="event-form"><div class="modal-content"><label>Nome do evento<input name="title" maxlength="120" value="${h(event?.title||'')}" placeholder="Ex.: Preparar materiais da Jinhsi" required></label><div class="form-columns"><label>Início no servidor<input name="start" type="datetime-local" value="${isoToServerInput(start,offset)}" required></label><label>Término no servidor<input name="end" type="datetime-local" value="${isoToServerInput(end,offset)}" required></label></div><label>Objetivos · um por linha<textarea name="tasks" rows="4" maxlength="10000" placeholder="Coletar materiais locais&#10;Concluir desafios semanais" ${event?.claimed?'readonly':''}>${h(event?.tasks.map(t=>t.text).join('\n')||'')}</textarea></label><h3>Recompensas previstas</h3><p class="footnote">Informadas por você. Não são recompensas oficiais verificadas e só entram no estoque após confirmar o recebimento.</p>${rewardSlots(event).map(i=>`<div class="reward-input-row"><label>Material ${i+1}<select name="reward-${i}" ${event?.claimed?'disabled':''}><option value="">Nenhum</option>${db.catalog.materials.map(m=>`<option value="${m.id}" ${reward[i]?.[0]===m.id?'selected':''}>${h(m.name)}</option>`).join('')}</select></label><label>Quantidade<input name="amount-${i}" type="number" min="0" max="1000000000" value="${reward[i]?.[1]||0}" ${event?.claimed?'disabled':''}></label></div>`).join('')}<p id="form-error" role="alert" class="form-error"></p></div><footer class="modal-footer">${button('Cancelar','close')}<button class="primary" type="submit">Salvar evento</button></footer></form>`);}
function importDialog(){pendingImport=null;openModal(modalHeader('Importar backup','Escolha um arquivo JSON ou cole o conteúdo. Nada é substituído antes da revisão.')+`<div class="modal-content"><label>Arquivo JSON<input type="file" id="backup-file" accept=".json,application/json"></label><label>Conteúdo do backup<textarea id="backup-text" rows="6" maxlength="2000000" placeholder="Cole o JSON exportado pelo Tacet"></textarea></label><p id="form-error" role="alert" class="form-error"></p><div id="import-preview"></div></div><footer class="modal-footer">${button('Cancelar','close')}${button('Validar e revisar','validate-import','','primary')}</footer>`);}
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function confirmDialog(title,body,action,attrs=''){openModal(modalHeader(title)+`<div class="modal-content">${body}</div><footer class="modal-footer">${button('Cancelar','close')}${button('Confirmar','confirm-'+action,attrs,'primary')}</footer>`);}

function draftState(){const goal=readGoal();validateGoal(goal,db);const next=clone(state()),index=next.goals.findIndex(g=>g.id===goal.id);if(index<0)next.goals.push(goal);else next.goals[index]=goal;return {next,goal};}
function stockEditor(materialId){const ids=materialId.startsWith('xp-')?db.catalog.materials.filter(m=>m.xpKind===(materialId==='xp-potion'?'potion':'energy')).map(m=>m.id):[materialId];const editor=document.querySelector('#goal-stock-editor');editor.hidden=false;editor.innerHTML=`<h3>Seu inventário · ${h(materialMeta(materialId,db).name)}</h3><p>Informe a quantidade total que você tem.</p><div class="stock-editor-items">${ids.map(id=>{const m=materialMeta(id,db);return `<label>${materialIcon(m)}<span>${h(m.name)}${m.xp?`<small>${fmt(m.xp)} EXP por item</small>`:''}</span><input type="number" min="0" max="1000000000" step="1" required data-goal-stock="${h(id)}" value="${state().inventory[id]||0}" aria-label="Estoque de ${h(m.name)}"></label>`;}).join('')}</div><div class="button-group">${button('Cancelar','cancel-goal-stock')}${button('Atualizar estoque','save-goal-stock','','primary')}</div>`;editor.scrollIntoView({block:'nearest',behavior:'smooth'});editor.querySelector('input')?.focus();}
const actions={
 'toggle-ascension':b=>{const field=b.closest('.combined-progress'),stage=field.querySelector('input[type=hidden]'),choices=ascensionChoices(Number(field.querySelector('input[type=number]').value),db.rules.caps,Number(field.dataset.maxAscension));if(choices.length===2)stage.value=Number(stage.value)===choices[0]?choices[1]:choices[0];updateGoalPreview();},
 'edit-goal-stock':b=>stockEditor(b.dataset.id),
 'cancel-goal-stock':()=>{const editor=document.querySelector('#goal-stock-editor');editor.hidden=true;editor.innerHTML='';},
 'save-goal-stock':()=>{const editor=document.querySelector('#goal-stock-editor'),next=clone(state());for(const input of editor.querySelectorAll('[data-goal-stock]')){if(input.value===''||!integer(input.valueAsNumber)){input.reportValidity();throw Error('Informe quantidades inteiras entre 0 e 1 bilhão.');}next.inventory[input.dataset.goalStock]=input.valueAsNumber;}store.commit(next);editor.hidden=true;editor.innerHTML='';render();updateGoalPreview();toast('Estoque atualizado.');},
 'finish-goal':()=>{const {next,goal}=draftState();const completed=completeGoal(next,goal.id,db);store.commit(completed);closeModal();render();toast('Feito! Evolução registrada e materiais consumidos. Você pode desfazer.');},
 close:closeModal,choose,add:b=>goalForm(newGoal(b.dataset.id,id())),edit:b=>goalForm(state().goals.find(g=>g.id===b.dataset.id)),
 'edit-char':b=>goalForm(state().goals.find(g=>g.charId===b.dataset.id)),detail:b=>detail(state().goals.find(g=>g.id===b.dataset.id)),complete:b=>{completion(state().goals.find(g=>g.id===b.dataset.id));addActualLedger(b.dataset.id);},
 reopen:b=>{const next=clone(state()),g=next.goals.find(g=>g.id===b.dataset.id);g.done=false;commit(next,'Meta reaberta.');},
 remove:b=>confirmDialog('Excluir esta meta?','<p>O inventário permanece como está. Você pode desfazer essa exclusão.</p>','remove',`data-id="${b.dataset.id}"`),
 'confirm-remove':b=>{const next=clone(state());next.goals=next.goals.filter(g=>g.id!==b.dataset.id);closeModal();commit(next,'Meta excluída. Use Desfazer para restaurar.');},
 'move-up':b=>move(b.dataset.id,-1),'move-down':b=>move(b.dataset.id,1),
 undo:()=>{store.undo();closeModal();render();toast('Última alteração desfeita.');},
 export:()=>{download(JSON.stringify(state(),null,2),`tacet-backup-${new Date().toISOString().slice(0,10)}.json`);toast('Backup exportado.');},
 recovery:()=>{const raw=store.storage?.getItem(`${STORAGE_KEY}:recovery`);if(!raw)throw Error('Nenhuma cópia de recuperação encontrada.');download(raw,'tacet-recuperacao.json');},
 import:importDialog,
 'validate-import':()=>{pendingImport=parseBackup(document.querySelector('#backup-text').value,db);document.querySelector('#form-error').textContent='';document.querySelector('#import-preview').innerHTML=`<h3>Backup válido</h3><p>${pendingImport.goals.length} metas, ${Object.keys(pendingImport.inventory).length} materiais e ${pendingImport.events.length} eventos.</p><p><b>Mesclar:</b> mantém metas, eventos e configurações atuais; adiciona itens novos e usa o maior estoque por material. Não soma duas cópias do mesmo estoque.</p><p><b>Substituir:</b> usa integralmente o backup validado. A operação pode ser desfeita.</p><div class="button-group">${button('Mesclar backup','merge-import','','primary')}${button('Substituir pelo backup','replace-import')}</div>`;},
 'merge-import':()=>{if(!pendingImport)throw Error('Valide o backup primeiro.');const next=mergeState(state(),pendingImport,db);closeModal();commit(next,'Backup mesclado sem duplicar o estoque.');},
 'replace-import':()=>{if(!pendingImport)throw Error('Valide o backup primeiro.');const next=pendingImport;closeModal();commit(next,'Backup importado.');},
 source:b=>{const m=materialMeta(b.dataset.id,db);openModal(modalHeader(m.name)+`<div class="modal-content"><h3>Onde obter</h3><p>${h(m.origin)}</p><p>${db.rules.activities[m.activity]?.waveplates||0} Waveplates por resgate da atividade. Rendimento médio não verificado.</p></div>`);},
 synthesize:b=>{const recipe=db.recipes.find(r=>r.id===b.dataset.id),count=Number(b.dataset.count);confirmDialog('Confirmar síntese',`<p>Registre após sintetizar no jogo:</p><ul>${Object.entries(recipe.inputs).map(([id,n])=>`<li>Consumir ${fmt(n*count)} ${h(materialMeta(id,db).name)}</li>`).join('')}${Object.entries(recipe.outputs).map(([id,n])=>`<li>Receber ${fmt(n*count)} ${h(materialMeta(id,db).name)}</li>`).join('')}</ul><p>Somente recursos livres. </p>`,'synthesis',`data-id="${recipe.id}" data-count="${count}"`);},
 'confirm-synthesis':b=>{const next=applySynthesis(state(),b.dataset.id,Number(b.dataset.count),db);closeModal();commit(next,'Síntese registrada; metas recalculadas.');},
 'new-event':()=>eventForm(),'edit-event':b=>eventForm(state().events.find(e=>e.id===b.dataset.id)),
 'remove-event':b=>confirmDialog('Excluir este evento?','<p>Você poderá restaurá-lo com Desfazer. Recompensas já recebidas permanecem no inventário.</p>','event-delete',`data-id="${b.dataset.id}"`),
 'confirm-event-delete':b=>{const next=clone(state());next.events=next.events.filter(e=>e.id!==b.dataset.id);closeModal();commit(next,'Evento excluído.');},
 claim:b=>confirmDialog('Registrar recebimento?','<p>Confirme que você recebeu as recompensas no jogo. Os valores cadastrados serão adicionados ao estoque uma única vez.</p>','claim',`data-id="${b.dataset.id}"`),
 'confirm-claim':b=>{const next=claimRewards(state(),b.dataset.id);closeModal();commit(next,'Recompensas adicionadas ao estoque.');},
 'event-list':()=>{eventView='list';render();},'event-calendar':()=>{eventView='calendar';render();},
 'prev-month':()=>{eventMonth=new Date(eventMonth.getFullYear(),eventMonth.getMonth()-1,1);render();},'next-month':()=>{eventMonth=new Date(eventMonth.getFullYear(),eventMonth.getMonth()+1,1);render();}
};
function move(goalId,delta){const next=clone(state()),index=next.goals.findIndex(g=>g.id===goalId);if(index+delta<0||index+delta>=next.goals.length)return;[next.goals[index],next.goals[index+delta]]=[next.goals[index+delta],next.goals[index]];commit(next,'Prioridade atualizada. Estoque redistribuído.');}
document.addEventListener('error',e=>{if(e.target instanceof HTMLImageElement)e.target.hidden=true;},true);
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;locked(()=>actions[b.dataset.action]?.(b)).catch(error=>{showConflict();const el=modal.open&&modal.querySelector('#form-error');if(el)el.textContent=error.message;else toast(error.message);});});
document.addEventListener('input',e=>{
 const el=e.target;if(el.closest('#settings-form')){settingsDraft=Object.fromEntries(new FormData(el.form));return;}if(el.closest('#goal-form')){if(!el.dataset.goalStock)updateGoalPreview();return;}
 if(el.id==='backup-text'){pendingImport=null;const preview=document.querySelector('#import-preview');if(preview)preview.innerHTML='';}
 if(el.id==='picker-search'){const query=el.value.trim().toLowerCase();let count=0;modal.querySelectorAll('.picker-character').forEach(button=>{button.hidden=!button.textContent.toLowerCase().includes(query);if(!button.hidden)count++;});modal.querySelector('#picker-empty').hidden=count>0;return;}
 if(el.dataset.filter==='search'){search=el.value;render(true);return;}
 if(el.dataset.stock){
  const n=el.valueAsNumber;if(el.value===''||!integer(n)){el.setCustomValidity('Informe um número inteiro entre 0 e 1 bilhão.');el.reportValidity();return;}
  el.setCustomValidity('');locked(()=>{const next=clone(state());next.inventory[el.dataset.stock]=n;store.commit(next);render(true);}).catch(error=>{showConflict();toast(error.message);});
 }
});
document.addEventListener('change',e=>{const el=e.target;if(el.name==='weapon-id'){const w=db.catalog.weapons.find(x=>x.id===el.value),saved=editingGoal.weapon?.id===el.value?editingGoal.weapon:null;document.querySelector('#weapon-progress').innerHTML=progressFields('weapon-current',saved?.current||{level:1,ascension:0,xp:0},'Arma atual',w)+progressFields('weapon-target',saved?.target||{level:20,ascension:0,xp:0},'Meta da arma',w);updateGoalPreview();}if(el.closest('#settings-form')){settingsDraft=Object.fromEntries(new FormData(el.form));return;}locked(async()=>{
 if(el.dataset.filter){if(el.dataset.filter==='element')element=el.value;if(el.dataset.filter==='weapon')weaponFilter=el.value;if(el.dataset.filter==='category')category=el.value;if(el.dataset.filter==='used')usedOnly=el.checked;render(true);}
 if(el.dataset.yield){const n=el.value===''?0:Number(el.value);if(!Number.isFinite(n)||n<0||n>1e9)throw Error('Informe um rendimento positivo válido.');const next=clone(state());next.settings.yields[el.dataset.yield]=n;commit(next);}
 if(el.dataset.task){const next=clone(state()),event=next.events.find(x=>x.id===el.dataset.task);if(event.claimed)throw Error('Recompensa já registrada.');event.tasks[Number(el.dataset.index)].done=el.checked;commit(next);}
 if(el.id==='backup-file'){const file=el.files[0];if(!file)return;if(file.size>2000000)throw Error('Limite de 2 MB por backup.');document.querySelector('#backup-text').value=await file.text();pendingImport=null;document.querySelector('#import-preview').innerHTML='';}
 }).catch(error=>{showConflict();toast(error.message);});});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('[data-goal-stock]')){e.preventDefault();document.querySelector('[data-action=save-goal-stock]').click();}});
document.addEventListener('submit',e=>{e.preventDefault();const form=e.target,fd=new FormData(form);locked(()=>{
 if(form.id==='goal-form'){const goal=readGoal();validateGoal(goal,db);const next=clone(state()),index=next.goals.findIndex(g=>g.id===goal.id);if(index>=0)next.goals[index]=goal;else next.goals.push(goal);store.commit(next);closeModal();render();toast('Meta salva. Materiais recalculados.');}
 if(form.id==='completion-form'){const consumption={},refunds={};for(const [key,value]of fd){if(key.startsWith('actual-'))consumption[key.slice(7)]=Number(value);if(key.startsWith('refund-'))refunds[key.slice(7)]=Number(value);}const next=completeGoal(state(),form.dataset.id,db,{characterXp:Number(fd.get('characterXp')),weaponXp:Number(fd.get('weaponXp')),consumption,refunds});closeModal();commit(next,'Evolução registrada. Você pode desfazer.');}
 if(form.id==='settings-form'){const next=clone(state()),changed=next.settings.unionLevel!==Number(fd.get('unionLevel'));next.settings={...next.settings,server:fd.get('server'),timeZone:fd.get('timeZone'),unionLevel:Number(fd.get('unionLevel')),dailyWaveplates:Number(fd.get('dailyWaveplates')),weeklyClaimsUsed:Number(fd.get('weeklyClaimsUsed')),weeklyPeriod:new Date(nextReset(Date.now(),db.rules.servers[fd.get('server')],true)).toISOString(),yields:changed?{}:next.settings.yields};store.commit(next);settingsDraft=null;render();toast(changed?'Configurações salvas; rendimentos limpos para o novo nível.':'Configurações salvas.');}
 if(form.id==='event-form'){
  const offset=db.rules.servers[state().settings.server],tasks=String(fd.get('tasks')).split('\n').map(t=>t.trim()).filter(Boolean).map(text=>({text,done:editingEvent?.tasks.find(t=>t.text===text)?.done||false}));
  const rewards=readEventRewards(fd,editingEvent);
  const event={id:editingEvent?.id||id(),title:String(fd.get('title')).trim(),kind:'personal',start:serverDateToISO(fd.get('start'),offset),end:serverDateToISO(fd.get('end'),offset),tasks,rewards,claimed:editingEvent?.claimed||false},next=clone(state()),index=next.events.findIndex(e=>e.id===event.id);
  if(index>=0)next.events[index]=event;else next.events.push(event);store.commit(next);closeModal();render();toast('Evento salvo na sua agenda.');
 }
 }).catch(error=>{showConflict();const el=form.querySelector('#form-error');if(el)el.textContent=error.message;else toast(error.message);});});
window.addEventListener('hashchange',()=>{route=nav.some(([key])=>key===location.hash.slice(1))?location.hash.slice(1):'summary';search='';element='';weaponFilter='';category='';render();window.scrollTo(0,0);});
window.addEventListener('storage',e=>{if(!store)return;store.observeStorage(e);showConflict();});
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
function refreshWeekly(){const next=new Date(nextReset(Date.now(),db.rules.servers[state().settings.server],true)).toISOString();if(state().settings.weeklyPeriod!==next){store.assertWritable();const updated=clone(state());updated.settings.weeklyClaimsUsed=0;updated.settings.weeklyPeriod=next;store.state=updated;store.persist();}}
async function boot(){
 try{
  const names=['catalog','rules','sources','recipes','events','character-art','weapon-stats'],loaded=await Promise.all(names.map(async name=>{const response=await fetch(`./data/${name}.json`);if(!response.ok)throw Error('Não foi possível carregar '+name);return response.json();}));db=Object.fromEntries(names.map((name,i)=>[name,loaded[i]]));for(const c of db.catalog.characters)c.imageHighRes=db['character-art']?.[c.id]?.card;
  await locked(()=>{const storage=getStorage(window),loadedState=loadState(storage,db);loadWarning=loadedState.warning||'';store=new Store(loadedState.state,db,storage);refreshWeekly();if(loadWarning)store.saveError=loadWarning;});route=nav.some(([key])=>key===location.hash.slice(1))?location.hash.slice(1):'summary';render();if(loadWarning)toast(loadWarning);
  registerPlannerTools({characters:db.catalog.characters,readPlan:()=>({goals:state().goals.map(g=>({id:g.id,character:g.charId,currentLevel:g.current.level,targetLevel:g.target.level,done:g.done})),materials:allocate(state().goals,state().inventory,db).totals}),startGoal:characterId=>{if(!db.catalog.characters.some(c=>c.id===characterId))throw Error('Personagem fora do catálogo.');goalForm(state().goals.find(g=>g.charId===characterId)||newGoal(characterId,id()));return {opened:true,characterId,saved:false};}});
  setInterval(()=>{if(modal.open||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;locked(()=>{if(store.conflicted){showConflict();return;}refreshWeekly();render();}).catch(error=>{showConflict();toast(error.message);});},60000);
 }catch(error){app.innerHTML=`<main class="boot-error"><h1>O terminal não carregou.</h1><p>${h(error.message)}</p><p>Abra a aplicação pelo servidor local; arquivos ES Modules não funcionam diretamente via file://.</p><button onclick="location.reload()">Tentar novamente</button></main>`;}
}
boot();
